import type { PrivatePlayerView, PublicMatchView } from "@hecliar/game-logic";
import { ActionStatus } from "./ActionStatus";
import { BidControls, type RaiseHandler } from "./BidControls";
import { DiceTray } from "./DiceTray";

export function GameTable({ publicMatch, privatePlayer, onRaise, onChallenge, onUseGadget }: { publicMatch: PublicMatchView; privatePlayer: PrivatePlayerView; onRaise: RaiseHandler; onChallenge(): Promise<void> | void; onUseGadget(target: number): Promise<void> | void }) {
  const bid = publicMatch.bid;
  return <main className="game-table" aria-label="Hecliar game table"><section className="table-surface opponent-surface" aria-label="Opponent"><div><p className="eyebrow">Opponent</p><strong>Robot</strong></div><DiceTray visibility="hidden" count={publicMatch.settings.diceCount} /><div className="scoreline" aria-label={`Score you ${publicMatch.score[0]}, robot ${publicMatch.score[1]}`}><span>{publicMatch.score[0]}</span><i>:</i><span>{publicMatch.score[1]}</span></div></section><section className="table-surface bid-surface"><p className="eyebrow">Current bid</p><h1>{bid ? `At least ${bid.quantity} dice show ${bid.face}` : "Open the bidding"}</h1><ActionStatus status={publicMatch.status} activeSeat={publicMatch.activeSeat} /></section><section className="table-surface hand-surface" aria-label="Your hand"><div className="hand-heading"><div><p className="eyebrow">Your hand</p><h2>Your dice</h2></div>{privatePlayer.gadget && <button className="gadget-chip" type="button" disabled={publicMatch.activeSeat !== 0 || publicMatch.status !== "active-turn"} onClick={() => onUseGadget(0)}>Use {privatePlayer.gadget}</button>}</div><DiceTray visibility="owner" dice={privatePlayer.ownDice} count={privatePlayer.ownDice.length} />{privatePlayer.scannerResult !== null && <p className="scanner-result">Scanner: the current bid is {privatePlayer.scannerResult ? "supported" : "not supported"}.</p>}<BidControls match={publicMatch} onRaise={onRaise} onChallenge={onChallenge} /></section></main>;
}
