export const HECLIAR_GAME_ABI = [
  // -- write --
  { type: "function", name: "createRoom", inputs: [{ name: "roomHash", type: "bytes32" }, { name: "diceCount", type: "uint8" }, { name: "gadgetsEnabled", type: "bool" }, { name: "ttl", type: "uint64" }], outputs: [{ type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "joinRoom", inputs: [{ name: "roomHash", type: "bytes32" }], outputs: [{ type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "setReady", inputs: [{ name: "matchId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "createRobotMatch", inputs: [{ name: "diceCount", type: "uint8" }, { name: "gadgetsEnabled", type: "bool" }, { name: "robot", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "payable" },
  { type: "function", name: "raise", inputs: [{ name: "matchId", type: "uint256" }, { name: "quantity", type: "uint8" }, { name: "face", type: "uint8" }, { name: "expectedSequence", type: "uint32" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "challenge", inputs: [{ name: "matchId", type: "uint256" }, { name: "expectedSequence", type: "uint32" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "settleChallenge", inputs: [{ name: "matchId", type: "uint256" }, { name: "settlement", type: "tuple", components: [{ name: "dieValues", type: "uint256[12]" }, { name: "dieSignatures", type: "bytes[][12]" }, { name: "effectiveCount", type: "uint256" }, { name: "effectiveCountSignatures", type: "bytes[]" }] }, { name: "expectedSequence", type: "uint32" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "fundAndStartNextRound", inputs: [{ name: "matchId", type: "uint256" }, { name: "expectedSequence", type: "uint32" }], outputs: [], stateMutability: "payable" },
  { type: "function", name: "useGadget", inputs: [{ name: "matchId", type: "uint256" }, { name: "encryptedTarget", type: "bytes" }, { name: "expectedSequence", type: "uint32" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "claimTurnTimeout", inputs: [{ name: "matchId", type: "uint256" }, { name: "expectedSequence", type: "uint32" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "claimAbandonment", inputs: [{ name: "matchId", type: "uint256" }, { name: "expectedSequence", type: "uint32" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "acceptRematch", inputs: [{ name: "matchId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  // -- read --
  { type: "function", name: "inspectRoom", inputs: [{ name: "roomHash", type: "bytes32" }], outputs: [{ type: "uint256" }, { type: "tuple", components: [{ name: "mode", type: "uint8" }, { name: "status", type: "uint8" }, { name: "players", type: "address[2]" }, { name: "diceCount", type: "uint8" }, { name: "gadgetsEnabled", type: "bool" }, { name: "ready", type: "bool[2]" }, { name: "activeSeat", type: "uint8" }, { name: "startingSeat", type: "uint8" }, { name: "roundNumber", type: "uint8" }, { name: "score", type: "uint8[2]" }, { name: "currentBid", type: "tuple", components: [{ name: "quantity", type: "uint8" }, { name: "face", type: "uint8" }, { name: "bidderSeat", type: "uint8" }, { name: "sequence", type: "uint32" }] }, { name: "actionSequence", type: "uint32" }, { name: "actionDeadline", type: "uint64" }, { name: "abandonmentDeadline", type: "uint64" }, { name: "rematchAccepted", type: "bool[2]" }] }, { type: "uint64" }], stateMutability: "view" },
  { type: "function", name: "getPublicMatch", inputs: [{ name: "matchId", type: "uint256" }], outputs: [{ type: "tuple", components: [{ name: "mode", type: "uint8" }, { name: "status", type: "uint8" }, { name: "players", type: "address[2]" }, { name: "diceCount", type: "uint8" }, { name: "gadgetsEnabled", type: "bool" }, { name: "ready", type: "bool[2]" }, { name: "activeSeat", type: "uint8" }, { name: "startingSeat", type: "uint8" }, { name: "roundNumber", type: "uint8" }, { name: "score", type: "uint8[2]" }, { name: "currentBid", type: "tuple", components: [{ name: "quantity", type: "uint8" }, { name: "face", type: "uint8" }, { name: "bidderSeat", type: "uint8" }, { name: "sequence", type: "uint32" }] }, { name: "actionSequence", type: "uint32" }, { name: "actionDeadline", type: "uint64" }, { name: "abandonmentDeadline", type: "uint64" }, { name: "rematchAccepted", type: "bool[2]" }] }], stateMutability: "view" },
  { type: "function", name: "getMyRoundHandles", inputs: [{ name: "matchId", type: "uint256" }], outputs: [{ type: "tuple", components: [{ name: "dice", type: "bytes32[6]" }, { name: "gadget", type: "bytes32" }, { name: "gadgetTarget", type: "bytes32" }, { name: "scannerResult", type: "bytes32" }] }], stateMutability: "view" },
  { type: "function", name: "getChallengeHandles", inputs: [{ name: "matchId", type: "uint256" }], outputs: [{ type: "tuple", components: [{ name: "dice", type: "bytes32[12]" }, { name: "effectiveCount", type: "bytes32" }, { name: "effectCodes", type: "bytes32[2]" }] }], stateMutability: "view" },
  { type: "function", name: "getRoundResult", inputs: [{ name: "matchId", type: "uint256" }, { name: "roundNumber", type: "uint8" }], outputs: [{ type: "tuple", components: [{ name: "settled", type: "bool" }, { name: "revealedRolls", type: "uint8[6][2]" }, { name: "challengedBid", type: "tuple", components: [{ name: "quantity", type: "uint8" }, { name: "face", type: "uint8" }, { name: "bidderSeat", type: "uint8" }, { name: "sequence", type: "uint32" }] }, { name: "baseCount", type: "uint8" }, { name: "effectiveCount", type: "uint256" }, { name: "winnerSeat", type: "uint8" }, { name: "resultingScore", type: "uint8[2]" }] }], stateMutability: "view" },
  { type: "function", name: "requiredRoundFee", inputs: [{ name: "diceCount", type: "uint8" }, { name: "gadgetsEnabled", type: "bool" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "matchByRoomHash", inputs: [{ name: "", type: "bytes32" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "nextMatchId", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
] as const;
